### ISSUE TITLE
Remember content page you are on across a reload.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift-labs/workshop-dashboard#12]
Use local storage to remember what part of workshop you are on when doing a reload.

**Comment by kaovilai** [comment]
Service workers should do the job.

**Comment by GrahamDumpleton** [comment]
Service workers look like unnecessary complexity. Not going to attempt to remember anything across browser reload. Will instead add a means to trigger a reload of the individual iframes instead. Possibly by having a refresh icon up in banner along side menu, or a menu option.

**Comment by GrahamDumpleton** [comment]
Closed in favour of #44.
