### ISSUE TITLE
Mention workshopper capability

### ISSUE THREAD

**Issue by kaovilai** [openshift-labs/workshop-dashboard#29]
add Workshopper adoc deployment instructions and new capabilities

New roles for source/bash blocks - 'execute', 'execute-1', 'execute-2'.

**Comment by GrahamDumpleton** [comment]
Have already documented what support have for roles in AsciiDoc, and support in general for AsciiDoc. What is documented is what will be supported for AsciiDoc. Not going to document some of the compatibility hacks to support old Workshopper content directory/file layout as not going to support that going forward. Is expected that existing content will be transitioned to new required directory/file layout.
