### ISSUE TITLE
"Useless" scrollbar

### ISSUE THREAD

**Issue by kaovilai** [openshift-labs/workshop-dashboard#30]
Workshop div can show useless scrollbar on systems with always visible scrollbar taking up valuable content space. 

It can result in single useless scrollbar. If content inside is longer, there will be another scrollbar that comes up. That is intended.

This issue is regarding the static scrollbar that stays there visible on system configured with always visible scrollbars such as by default Windows systems. macOS may also inherit this issue if user have set their setting to show scrollbar.
![image](https://user-images.githubusercontent.com/11228024/60560518-1fd2d000-9d1e-11e9-8a0b-0a76d619b6a7.png)

For testing on macOS
Set the following
![image](https://user-images.githubusercontent.com/11228024/60560472-f6b23f80-9d1d-11e9-96ab-49405512ab2c.png)

Preliminary testing inside Chrome's DevTools shows that css that targets `iframe-div` class were not inherited properly.

Applying `overflow: hidden` to the `div` directly solves this issue.

Possible fix include adding the following to CSS
```
div#workshop-div {
    overflow: hidden;
}
```
![image](https://user-images.githubusercontent.com/11228024/60560582-57417c80-9d1e-11e9-9ea8-58d6cd31b9d0.png)

cc: @thoraxe

**Comment by GrahamDumpleton** [comment]
The issue relates to the `overflow-y: scroll` that is defined in CSS for `.iframe-div`. If that is removed, works okay then on desktop. Need to check whether removing that will cause an issue on a tablet with iOS though. It may have in part been added because of that.

**Comment by GrahamDumpleton** [comment]
Fix in 3.4.1.
