### ISSUE TITLE
Remote workshop content source

### ISSUE THREAD

**Issue by kaovilai** [openshift-labs/workshop-dashboard#31]
Right now in README.md it is suggested to attach custom workshop image if you have one with 
`--param TERMINAL_IMAGE=`
If the base workshop-dashboard image is provided required packages, it would be nice to have workshops created directly without creating new Dockerfile.

**Comment by GrahamDumpleton** [comment]
Unless misunderstand what you are after, this should be be possible using ``DOWNLOAD_URL`` and ``WORKSHOP_FILE``. Use of images is still recommended to allow people to pull images and use a workshop in a disconnected environment.
