### ISSUE TITLE
terminal typing cursor may be hidden behind other windows

### ISSUE THREAD

**Issue by kaovilai** [openshift-labs/workshop-dashboard#38]
See
https://youtu.be/ZqbsI4WTxMQ

**Comment by kaovilai** [comment]
Environment in the recording
workshop-dashboard
-terminal region
--lower-split-terminal
---tmux
----half right pane.

**Comment by GrahamDumpleton** [comment]
Does it occur when you aren't using tmux? Need to determine if this isn't an issue related to tmux.

**Comment by kaovilai** [comment]
I have seen it happen outside of tmux. Most likely after multiple window resizing.

**Comment by GrahamDumpleton** [comment]
Have removed border padding within iframes. Seems to improve things a bit. Going to close this until see more evidence of it.
