### ISSUE TITLE
signed-in user on long workshop sessions can get kicked out and have to relogin via openshift

### ISSUE THREAD

**Issue by kaovilai** [openshift-labs/workshop-dashboard#39]
symptoms of a student locked out due to some credentials timeout
- going to next instruction page result in a blank page.
- refreshing dashboard redirects them to openshift login screen

**Comment by GrahamDumpleton** [comment]
Have explained this to you before. It will occur when using OpenShift auth for login.

In general it would not be expected to occur for an actual workshop using a cluster provisioned for the workshop, as the start of the time period for a specific users password expiration should only start when the attendee first logged in. The workshop would be over before the timeout occurs, unless you are going to run 24 hour workshops.

It should thus only be noticeable when developing content and you keep cycling over the workshop in the same cluster time and time again, as eventually there is a chance that you might be going through the workshop content when the timeout expires.

If you are saying this has happened in a real workshop, you need to explain more about how workshop was being deployed, what login user had, and the time line of when cluster was deployed, when workshop started, and also whether anyone (including automated setup scripts) besides the person doing the workshop, would have logged in the user and caused timeout to be started for the login.

For RHPDS clusters, one option is you override the 24 hour timeout and set it to 3 days for the workshops if worried, or your deployment of the workshop is starting the timeout as it logins in the cluster admin user during cluster setup, and that is what they use.

**Comment by kaovilai** [comment]
Got it.
